# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
System.create(name: "Super Nintendo", company: "Nintendo")
System.create(name: "Nintendo 64", company: "Nintendo")
System.create(name: "GameCube", company: "Nintendo")
System.create(name: "Nintendo Wii", company: "Nintendo")
System.create(name: "Wii U", company: "Nintendo")
System.create(name: "Nintendo Switch", company: "Nintendo")
System.create(name: "GameBoy", company: "Nintendo")
System.create(name: "GameBoy Advanced", company: "Nintendo")
System.create(name: "Nintendo DS", company: "Nintendo")
System.create(name: "Nintendo 3DS", company: "Nintendo")
System.create(name: "Atari", company: "Atari inc")
System.create(name: "Sega Genesis", company: "Sega")
System.create(name: "Dreamcast", company: "Sega")
System.create(name: "PlayStation", company: "Sony")
System.create(name: "PlayStation 2", company: "Sony")
System.create(name: "PlayStation 3", company: "Sony")
System.create(name: "PlayStation 4", company: "Sony")
System.create(name: "PSP", company: "Sony")
System.create(name: "PlayStation Vita", company: "Sony")
System.create(name: "Xbox", company: "Microsoft")
System.create(name: "Xbox 360", company: "Microsoft")
System.create(name: "Xbox One", company: "Microsoft")
System.create(name: "PC", company: "Your Computer")
System.create(name: "Other", company: "Unknown")